---
- name: ANSISTRANO | download | Create release folder
  file:
    state: directory
    path: "{{ ansistrano_release_path.stdout }}"
  
- name: ANSISTRANO | download | Download artifact
  get_url:
    url: "{{ ansistrano_get_url }}"
    dest: "{{ ansistrano_release_path.stdout }}/{{ ansistrano_get_url | basename }}"
    url_username: "{{ ansistrano_get_username | default(omit) }}"
    url_password: "{{ ansistrano_get_password | default(omit) }}"
    validate_certs: "{{ ansistrano_get_validate_certs | default(omit) }}"
    checksum: "{{ ansistrano_get_checksum | default(omit) }}"
