---
- name: ANSISTRANO | download | Create release folder
  file:
    state: directory
    path: "{{ ansistrano_release_path.stdout }}"

- name: ANSISTRANO | download | Download artifact without credentials
  get_url:
    url: "{{ ansistrano_get_url }}"
    dest: "{{ ansistrano_release_path.stdout }}/{{ ansistrano_get_url | basename }}"
    validate_certs: "{{ ansistrano_get_validate_certs }}"
  when: ansistrano_get_username is not defined
  
- name: ANSISTRANO | download | Download artifact with credentials
  get_url:
    url: "{{ ansistrano_get_url }}"
    dest: "{{ ansistrano_release_path.stdout }}/{{ ansistrano_get_url | basename }}"
    url_username: "{{ ansistrano_get_username }}"
    url_password: "{{ ansistrano_get_password }}"
    validate_certs: "{{ ansistrano_get_validate_certs }}"
  when: ansistrano_get_username is defined
